# Generated by Django 3.2.4 on 2021-09-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_productgallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productgallery',
            options={'verbose_name': 'productgallery', 'verbose_name_plural': 'product gallery'},
        ),
        migrations.AddField(
            model_name='product',
            name='alt_images',
            field=models.ImageField(blank=True, upload_to='pictures/products'),
        ),
    ]
