# Generated by Django 3.2.4 on 2022-05-04 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_auto_20210907_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='BannerGallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subtitle', models.TextField(blank=True, max_length=500)),
                ('heading', models.TextField(blank=True, max_length=500)),
                ('description', models.TextField(blank=True, max_length=500)),
                ('image', models.ImageField(max_length=255, upload_to='banner/images')),
            ],
        ),
    ]
