# Generated by Django 3.2.4 on 2022-05-04 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_bannergallery'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannergallery',
            options={'verbose_name': 'bannergalleru', 'verbose_name_plural': 'banner gallery'},
        ),
    ]
