# Generated by Django 3.2.4 on 2022-05-04 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_alter_bannergallery_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bannergallery',
            options={'verbose_name': 'bannergallery', 'verbose_name_plural': 'banner gallery'},
        ),
    ]
